# docker-compose.yml
version: '3'

services:
  serving:
    build:
      context: ./
      dockerfile: ./Dockerfile.serving
      #args:
    image: ift6758/serving:0.0.1
    ports: 
      - 5001:5001
#    environment:
#      DOCKER_ENV_VAR = ${LOCAL_ENV_VAR}
#      COMET_API_KEY = ${COMET_API_KEY}
###### Uncomment below when you're ready to add the final notebook container to your docker compose
#  streamlit:
#    build:
#      context: ./
#      dockerfile: ./Dockerfile.streamlit
##      args:
##        ARG: <ARG>
#    image: ift6758/streamlit:0.0.1
#    ports:
#      - 0.0.0.0:8892:8892
#    environment:
#      SERVING_IP: 0.0.0.0
#      SERVING_PORT: 5001
      

     
